# Generated by Django 6.0 on 2025-12-17 20:53

import todo_list.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, null=True, validators=[todo_list.utils.validate_future_date], verbose_name='End Date'),
        ),
    ]
